//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 03:52:15 PM WAT 
//


package com.swifta.ussd.ussdapi;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.swifta.leadway.ussdapi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotifyUssdReception_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdReception");
    private final static QName _NotifyUssdReceptionResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdReceptionResponse");
    private final static QName _NotifyUssdAbort_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdAbort");
    private final static QName _NotifyUssdAbortResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdAbortResponse");
    private final static QName _ServiceException_QNAME = new QName("http://www.csapi.org/schema/parlayx/common/v2_1", "ServiceException");
    private final static QName _PolicyException_QNAME = new QName("http://www.csapi.org/schema/parlayx/common/v2_1", "PolicyException");
    private final static QName _StartUSSDNotification_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "startUSSDNotification");
    private final static QName _StartUSSDNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "startUSSDNotificationResponse");
    private final static QName _StopUSSDNotification_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "stopUSSDNotification");
    private final static QName _StopUSSDNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "stopUSSDNotificationResponse");
    private final static QName _RedirectUssd_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/redirect/v1_0/local", "redirectUssd");
    private final static QName _RedirectUssdResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/redirect/v1_0/local", "redirectUssdResponse");
    private final static QName _SendUssd_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", "sendUssd");
    private final static QName _SendUssdResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", "sendUssdResponse");
    private final static QName _SendUssdAbort_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", "sendUssdAbort");
    private final static QName _SendUssdAbortResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", "sendUssdAbortResponse");
    private final static QName _SendUssdSwitch_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", "sendUssdSwitch");
    private final static QName _SendUssdSwitchResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", "sendUssdSwitchResponse");
    private final static QName _RequestSOAPHeader_QNAME = new QName("http://www.huawei.com.cn/schema/common/v2_1", "RequestSOAPHeader");
    private final static QName _NotifySOAPHeader_QNAME = new QName("http://www.huawei.com.cn/schema/common/v2_1", "NotifySOAPHeader");
    private final static QName _SendSms_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "sendSms");
    private final static QName _SendSmsResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "sendSmsResponse");
    private final static QName _SendSmsLogo_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "sendSmsLogo");
    private final static QName _SendSmsLogoResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "sendSmsLogoResponse");
    private final static QName _SendSmsRingtone_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "sendSmsRingtone");
    private final static QName _SendSmsRingtoneResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "sendSmsRingtoneResponse");
    private final static QName _GetSmsDeliveryStatus_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "getSmsDeliveryStatus");
    private final static QName _GetSmsDeliveryStatusResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", "getSmsDeliveryStatusResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.swifta.leadway.ussdapi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifyUssdReception }
     * 
     */
    public NotifyUssdReception createNotifyUssdReception() {
        return new NotifyUssdReception();
    }

    /**
     * Create an instance of {@link NotifyUssdReceptionResponse }
     * 
     */
    public NotifyUssdReceptionResponse createNotifyUssdReceptionResponse() {
        return new NotifyUssdReceptionResponse();
    }

    /**
     * Create an instance of {@link NotifyUssdAbort }
     * 
     */
    public NotifyUssdAbort createNotifyUssdAbort() {
        return new NotifyUssdAbort();
    }

    /**
     * Create an instance of {@link NotifyUssdAbortResponse }
     * 
     */
    public NotifyUssdAbortResponse createNotifyUssdAbortResponse() {
        return new NotifyUssdAbortResponse();
    }

    /**
     * Create an instance of {@link NamedParameterList }
     * 
     */
    public NamedParameterList createNamedParameterList() {
        return new NamedParameterList();
    }

    /**
     * Create an instance of {@link NamedParameter }
     * 
     */
    public NamedParameter createNamedParameter() {
        return new NamedParameter();
    }

    /**
     * Create an instance of {@link ServiceException }
     * 
     */
    public ServiceException createServiceException() {
        return new ServiceException();
    }

    /**
     * Create an instance of {@link PolicyException }
     * 
     */
    public PolicyException createPolicyException() {
        return new PolicyException();
    }

    /**
     * Create an instance of {@link TimeMetric }
     * 
     */
    public TimeMetric createTimeMetric() {
        return new TimeMetric();
    }

    /**
     * Create an instance of {@link ChargingInformation }
     * 
     */
    public ChargingInformation createChargingInformation() {
        return new ChargingInformation();
    }

    /**
     * Create an instance of {@link SimpleReference }
     * 
     */
    public SimpleReference createSimpleReference() {
        return new SimpleReference();
    }

    /**
     * Create an instance of {@link ServiceError }
     * 
     */
    public ServiceError createServiceError() {
        return new ServiceError();
    }

    /**
     * Create an instance of {@link StartUSSDNotification }
     * 
     */
    public StartUSSDNotification createStartUSSDNotification() {
        return new StartUSSDNotification();
    }

    /**
     * Create an instance of {@link StartUSSDNotificationResponse }
     * 
     */
    public StartUSSDNotificationResponse createStartUSSDNotificationResponse() {
        return new StartUSSDNotificationResponse();
    }

    /**
     * Create an instance of {@link StopUSSDNotification }
     * 
     */
    public StopUSSDNotification createStopUSSDNotification() {
        return new StopUSSDNotification();
    }

    /**
     * Create an instance of {@link StopUSSDNotificationResponse }
     * 
     */
    public StopUSSDNotificationResponse createStopUSSDNotificationResponse() {
        return new StopUSSDNotificationResponse();
    }

    /**
     * Create an instance of {@link RedirectUssd }
     * 
     */
    public RedirectUssd createRedirectUssd() {
        return new RedirectUssd();
    }

    /**
     * Create an instance of {@link RedirectUssdResponse }
     * 
     */
    public RedirectUssdResponse createRedirectUssdResponse() {
        return new RedirectUssdResponse();
    }

    /**
     * Create an instance of {@link NamedParameterList2 }
     * 
     */
    public NamedParameterList2 createNamedParameterList2() {
        return new NamedParameterList2();
    }

    /**
     * Create an instance of {@link NamedParameter2 }
     * 
     */
    public NamedParameter2 createNamedParameter2() {
        return new NamedParameter2();
    }

    /**
     * Create an instance of {@link SendUssd }
     * 
     */
    public SendUssd createSendUssd() {
        return new SendUssd();
    }

    /**
     * Create an instance of {@link SendUssdResponse }
     * 
     */
    public SendUssdResponse createSendUssdResponse() {
        return new SendUssdResponse();
    }

    /**
     * Create an instance of {@link SendUssdAbort }
     * 
     */
    public SendUssdAbort createSendUssdAbort() {
        return new SendUssdAbort();
    }

    /**
     * Create an instance of {@link SendUssdAbortResponse }
     * 
     */
    public SendUssdAbortResponse createSendUssdAbortResponse() {
        return new SendUssdAbortResponse();
    }

    /**
     * Create an instance of {@link SendUssdSwitch }
     * 
     */
    public SendUssdSwitch createSendUssdSwitch() {
        return new SendUssdSwitch();
    }

    /**
     * Create an instance of {@link SendUssdSwitchResponse }
     * 
     */
    public SendUssdSwitchResponse createSendUssdSwitchResponse() {
        return new SendUssdSwitchResponse();
    }

    /**
     * Create an instance of {@link NamedParameterList3 }
     * 
     */
    public NamedParameterList3 createNamedParameterList3() {
        return new NamedParameterList3();
    }

    /**
     * Create an instance of {@link NamedParameter3 }
     * 
     */
    public NamedParameter3 createNamedParameter3() {
        return new NamedParameter3();
    }

    /**
     * Create an instance of {@link RequestSOAPHeader }
     * 
     */
    public RequestSOAPHeader createRequestSOAPHeader() {
        return new RequestSOAPHeader();
    }

    /**
     * Create an instance of {@link NotifySOAPHeader }
     * 
     */
    public NotifySOAPHeader createNotifySOAPHeader() {
        return new NotifySOAPHeader();
    }

    /**
     * Create an instance of {@link SendSms }
     * 
     */
    public SendSms createSendSms() {
        return new SendSms();
    }

    /**
     * Create an instance of {@link SendSmsResponse }
     * 
     */
    public SendSmsResponse createSendSmsResponse() {
        return new SendSmsResponse();
    }

    /**
     * Create an instance of {@link SendSmsLogo }
     * 
     */
    public SendSmsLogo createSendSmsLogo() {
        return new SendSmsLogo();
    }

    /**
     * Create an instance of {@link SendSmsLogoResponse }
     * 
     */
    public SendSmsLogoResponse createSendSmsLogoResponse() {
        return new SendSmsLogoResponse();
    }

    /**
     * Create an instance of {@link SendSmsRingtone }
     * 
     */
    public SendSmsRingtone createSendSmsRingtone() {
        return new SendSmsRingtone();
    }

    /**
     * Create an instance of {@link SendSmsRingtoneResponse }
     * 
     */
    public SendSmsRingtoneResponse createSendSmsRingtoneResponse() {
        return new SendSmsRingtoneResponse();
    }

    /**
     * Create an instance of {@link GetSmsDeliveryStatus }
     * 
     */
    public GetSmsDeliveryStatus createGetSmsDeliveryStatus() {
        return new GetSmsDeliveryStatus();
    }

    /**
     * Create an instance of {@link GetSmsDeliveryStatusResponse }
     * 
     */
    public GetSmsDeliveryStatusResponse createGetSmsDeliveryStatusResponse() {
        return new GetSmsDeliveryStatusResponse();
    }

    /**
     * Create an instance of {@link DeliveryInformation }
     * 
     */
    public DeliveryInformation createDeliveryInformation() {
        return new DeliveryInformation();
    }

    /**
     * Create an instance of {@link SmsMessage }
     * 
     */
    public SmsMessage createSmsMessage() {
        return new SmsMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdReception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdReception")
    public JAXBElement<NotifyUssdReception> createNotifyUssdReception(NotifyUssdReception value) {
        return new JAXBElement<NotifyUssdReception>(_NotifyUssdReception_QNAME, NotifyUssdReception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdReceptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdReceptionResponse")
    public JAXBElement<NotifyUssdReceptionResponse> createNotifyUssdReceptionResponse(NotifyUssdReceptionResponse value) {
        return new JAXBElement<NotifyUssdReceptionResponse>(_NotifyUssdReceptionResponse_QNAME, NotifyUssdReceptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdAbort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdAbort")
    public JAXBElement<NotifyUssdAbort> createNotifyUssdAbort(NotifyUssdAbort value) {
        return new JAXBElement<NotifyUssdAbort>(_NotifyUssdAbort_QNAME, NotifyUssdAbort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdAbortResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdAbortResponse")
    public JAXBElement<NotifyUssdAbortResponse> createNotifyUssdAbortResponse(NotifyUssdAbortResponse value) {
        return new JAXBElement<NotifyUssdAbortResponse>(_NotifyUssdAbortResponse_QNAME, NotifyUssdAbortResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/common/v2_1", name = "ServiceException")
    public JAXBElement<ServiceException> createServiceException(ServiceException value) {
        return new JAXBElement<ServiceException>(_ServiceException_QNAME, ServiceException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/common/v2_1", name = "PolicyException")
    public JAXBElement<PolicyException> createPolicyException(PolicyException value) {
        return new JAXBElement<PolicyException>(_PolicyException_QNAME, PolicyException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartUSSDNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "startUSSDNotification")
    public JAXBElement<StartUSSDNotification> createStartUSSDNotification(StartUSSDNotification value) {
        return new JAXBElement<StartUSSDNotification>(_StartUSSDNotification_QNAME, StartUSSDNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartUSSDNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "startUSSDNotificationResponse")
    public JAXBElement<StartUSSDNotificationResponse> createStartUSSDNotificationResponse(StartUSSDNotificationResponse value) {
        return new JAXBElement<StartUSSDNotificationResponse>(_StartUSSDNotificationResponse_QNAME, StartUSSDNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StopUSSDNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "stopUSSDNotification")
    public JAXBElement<StopUSSDNotification> createStopUSSDNotification(StopUSSDNotification value) {
        return new JAXBElement<StopUSSDNotification>(_StopUSSDNotification_QNAME, StopUSSDNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StopUSSDNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "stopUSSDNotificationResponse")
    public JAXBElement<StopUSSDNotificationResponse> createStopUSSDNotificationResponse(StopUSSDNotificationResponse value) {
        return new JAXBElement<StopUSSDNotificationResponse>(_StopUSSDNotificationResponse_QNAME, StopUSSDNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RedirectUssd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/redirect/v1_0/local", name = "redirectUssd")
    public JAXBElement<RedirectUssd> createRedirectUssd(RedirectUssd value) {
        return new JAXBElement<RedirectUssd>(_RedirectUssd_QNAME, RedirectUssd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RedirectUssdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/redirect/v1_0/local", name = "redirectUssdResponse")
    public JAXBElement<RedirectUssdResponse> createRedirectUssdResponse(RedirectUssdResponse value) {
        return new JAXBElement<RedirectUssdResponse>(_RedirectUssdResponse_QNAME, RedirectUssdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUssd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", name = "sendUssd")
    public JAXBElement<SendUssd> createSendUssd(SendUssd value) {
        return new JAXBElement<SendUssd>(_SendUssd_QNAME, SendUssd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUssdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", name = "sendUssdResponse")
    public JAXBElement<SendUssdResponse> createSendUssdResponse(SendUssdResponse value) {
        return new JAXBElement<SendUssdResponse>(_SendUssdResponse_QNAME, SendUssdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUssdAbort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", name = "sendUssdAbort")
    public JAXBElement<SendUssdAbort> createSendUssdAbort(SendUssdAbort value) {
        return new JAXBElement<SendUssdAbort>(_SendUssdAbort_QNAME, SendUssdAbort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUssdAbortResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", name = "sendUssdAbortResponse")
    public JAXBElement<SendUssdAbortResponse> createSendUssdAbortResponse(SendUssdAbortResponse value) {
        return new JAXBElement<SendUssdAbortResponse>(_SendUssdAbortResponse_QNAME, SendUssdAbortResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUssdSwitch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", name = "sendUssdSwitch")
    public JAXBElement<SendUssdSwitch> createSendUssdSwitch(SendUssdSwitch value) {
        return new JAXBElement<SendUssdSwitch>(_SendUssdSwitch_QNAME, SendUssdSwitch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendUssdSwitchResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", name = "sendUssdSwitchResponse")
    public JAXBElement<SendUssdSwitchResponse> createSendUssdSwitchResponse(SendUssdSwitchResponse value) {
        return new JAXBElement<SendUssdSwitchResponse>(_SendUssdSwitchResponse_QNAME, SendUssdSwitchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestSOAPHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.huawei.com.cn/schema/common/v2_1", name = "RequestSOAPHeader")
    public JAXBElement<RequestSOAPHeader> createRequestSOAPHeader(RequestSOAPHeader value) {
        return new JAXBElement<RequestSOAPHeader>(_RequestSOAPHeader_QNAME, RequestSOAPHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifySOAPHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.huawei.com.cn/schema/common/v2_1", name = "NotifySOAPHeader")
    public JAXBElement<NotifySOAPHeader> createNotifySOAPHeader(NotifySOAPHeader value) {
        return new JAXBElement<NotifySOAPHeader>(_NotifySOAPHeader_QNAME, NotifySOAPHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSms }{@code >}}
     *
     * @return
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "sendSms")
    public JAXBElement<SendSms> createSendSms(SendSms value) {
        return new JAXBElement<SendSms>(_SendSms_QNAME, SendSms.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSmsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "sendSmsResponse")
    public JAXBElement<SendSmsResponse> createSendSmsResponse(SendSmsResponse value) {
        return new JAXBElement<SendSmsResponse>(_SendSmsResponse_QNAME, SendSmsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSmsLogo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "sendSmsLogo")
    public JAXBElement<SendSmsLogo> createSendSmsLogo(SendSmsLogo value) {
        return new JAXBElement<SendSmsLogo>(_SendSmsLogo_QNAME, SendSmsLogo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSmsLogoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "sendSmsLogoResponse")
    public JAXBElement<SendSmsLogoResponse> createSendSmsLogoResponse(SendSmsLogoResponse value) {
        return new JAXBElement<SendSmsLogoResponse>(_SendSmsLogoResponse_QNAME, SendSmsLogoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSmsRingtone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "sendSmsRingtone")
    public JAXBElement<SendSmsRingtone> createSendSmsRingtone(SendSmsRingtone value) {
        return new JAXBElement<SendSmsRingtone>(_SendSmsRingtone_QNAME, SendSmsRingtone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSmsRingtoneResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "sendSmsRingtoneResponse")
    public JAXBElement<SendSmsRingtoneResponse> createSendSmsRingtoneResponse(SendSmsRingtoneResponse value) {
        return new JAXBElement<SendSmsRingtoneResponse>(_SendSmsRingtoneResponse_QNAME, SendSmsRingtoneResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSmsDeliveryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "getSmsDeliveryStatus")
    public JAXBElement<GetSmsDeliveryStatus> createGetSmsDeliveryStatus(GetSmsDeliveryStatus value) {
        return new JAXBElement<GetSmsDeliveryStatus>(_GetSmsDeliveryStatus_QNAME, GetSmsDeliveryStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSmsDeliveryStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", name = "getSmsDeliveryStatusResponse")
    public JAXBElement<GetSmsDeliveryStatusResponse> createGetSmsDeliveryStatusResponse(GetSmsDeliveryStatusResponse value) {
        return new JAXBElement<GetSmsDeliveryStatusResponse>(_GetSmsDeliveryStatusResponse_QNAME, GetSmsDeliveryStatusResponse.class, null, value);
    }

}
