//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 03:52:15 PM WAT 
//


package com.swifta.ussd.ussdapi;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for redirectUssd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="redirectUssd"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="senderCB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="receiveCB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="msIsdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="serviceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="extenionInfo" type="{http://www.csapi.org/schema/parlayx/ussd/redirect/v1_0/local}NamedParameterList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redirectUssd", namespace = "http://www.csapi.org/schema/parlayx/ussd/redirect/v1_0/local", propOrder = {
    "senderCB",
    "receiveCB",
    "msIsdn",
    "serviceCode",
    "extenionInfo"
})
public class RedirectUssd {

    @XmlElement(required = true)
    protected String senderCB;
    @XmlElement(required = true)
    protected String receiveCB;
    @XmlElement(required = true)
    protected String msIsdn;
    protected String serviceCode;
    protected NamedParameterList2 extenionInfo;

    /**
     * Gets the value of the senderCB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderCB() {
        return senderCB;
    }

    /**
     * Sets the value of the senderCB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderCB(String value) {
        this.senderCB = value;
    }

    /**
     * Gets the value of the receiveCB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiveCB() {
        return receiveCB;
    }

    /**
     * Sets the value of the receiveCB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiveCB(String value) {
        this.receiveCB = value;
    }

    /**
     * Gets the value of the msIsdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsIsdn() {
        return msIsdn;
    }

    /**
     * Sets the value of the msIsdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsIsdn(String value) {
        this.msIsdn = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the extenionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NamedParameterList2 }
     *     
     */
    public NamedParameterList2 getExtenionInfo() {
        return extenionInfo;
    }

    /**
     * Sets the value of the extenionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedParameterList2 }
     *     
     */
    public void setExtenionInfo(NamedParameterList2 value) {
        this.extenionInfo = value;
    }

}
